services:
  postgres:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    env_file:
      .env
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data